
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres  
  password: pedro123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: list_development
